#!/bin/bash

SUDO=sudo

while getopts "shy" opt; do
	case $opt in
	    s)
		SUDO=""
		;;
	    y)
		DONTPROMPT="-y"
		;;
	    h)
		cat << EOF
$0 [-sy]
Options:
    -s : don't try running sudo. Useful in CI builds when you don't need sudo
         invocations.
    -y : don't prompt for install confirmation.
EOF
		exit
		;;
	esac
done

DIST_ID="$(lsb_release -a 2> /dev/null | awk '/Distributor ID:/{print $3}')"

case "$DIST_ID" in
    Ubuntu)
	UBUNTU_RELEASE="$(lsb_release -a 2> /dev/null | awk '/Release:/{print $2}')"
	UBUNTU_MAJOR="$(echo "$UBUNTU_RELEASE" | cut -d . -f 1)"
	;;
    Debian|Linuxmint)
	# Assume latest Ubuntu LTS
	UBUNTU_MAJOR=24
	;;
    *)
	# Fallback - check if apt is available at all
	if ! which apt &> /dev/null; then
		echo "This machine doesn't appear to be running Ubuntu or any apt-compatible distro." >&2
		exit 1
	fi
	# Assume latest Ubuntu LTS
	UBUNTU_MAJOR=24
	;;
esac

PACKAGES="build-essential cmake pkg-config automake autoconf libtool unzip"

if [ "$UBUNTU_MAJOR" -lt 14 ]; then
	echo "Your Ubuntu release ($UBUNTU_RELEASE) is too old." \
	    "libacfutils requires at least Ubuntu 14.04." >&2
	exit 1
elif [ "$UBUNTU_MAJOR" -eq 14 ]; then
	PACKAGES="$PACKAGES qt4-qmake qt4-dev-tools"
elif [ "$UBUNTU_MAJOR" -lt 21 ]; then
	PACKAGES="$PACKAGES qt5-qmake qt5-default"
else
	PACKAGES="$PACKAGES qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools"
fi


MINIMAL=0
while getopts "m" o; do
	case "${o}" in
	m)
		MINIMAL=1
		;;
	*)
		echo "Unknown option $o." >&2
		exit 1
		;;
	esac
done

if [ "$MINIMAL" -eq 0 ]; then
	PACKAGES="$PACKAGES libxcursor-dev libglu1-mesa-dev \
	    libpulse-dev libasound2-dev \
	    mingw-w64-x86-64-dev gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64"
fi

$SUDO apt-get install $DONTPROMPT $PACKAGES
