#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2024 Saso Kiselkov. All rights reserved.

if [[ $(uname) = "Linux" ]]; then
	LIBCLIPBOARD="libclipboard-linux-64"
	GNU_SED="sed"
else
	LIBCLIPBOARD="libclipboard-mac-64"
	ARCH_FLAGS="-DCMAKE_OSX_ARCHITECTURES='arm64;x86_64' \
	    -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0"
	GNU_SED="gsed"
fi
LIBCLIPBOARD_ARCHIVE="libclipboard-1.0.tar.bz2"

set -e

if [[ "$do_clean" == "1" ]]; then
	rm -rf "$LIBCLIPBOARD"
	exit
fi

if ! [ -f "$LIBCLIPBOARD/install/lib/libclipboard.a" ]; then
	rm -rf "$LIBCLIPBOARD"
	tar xjf "$LIBCLIPBOARD_ARCHIVE"
	mv "libclipboard-1.0" "$LIBCLIPBOARD"
	cd "$LIBCLIPBOARD"
	cmake -DCMAKE_C_FLAGS="-fPIC" \
	    -DCMAKE_INSTALL_PREFIX:PATH="$(pwd)/install" \
	    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
	    $ARCH_FLAGS \
	    .
	make -j4
	make install
	"$GNU_SED" -i 's|libdir=${exec_prefix}/|libdir=${exec_prefix}/lib|g' \
	    "install/lib/pkgconfig/libclipboard.pc"
fi
